version: '3'
services:
  geoserver:
    image: geoserver:2.21.3
    ports:
      - 8081:8080
    depends_on:
      - postgresql

  postgresql:
    image: geoserver_postgresql
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

