version: '3'

services:
  mqsrv:
    image: apache/rocketmq:4.9.1
    container_name: mqsrv
    command: sh mqnamesrv /bin/bash
    environment:
      MAX_POSSIBLE_HEAP: 100000000
    ports:
      - "9876:9876"
      - "10909:10909"

  mqbroker:
    image: apache/rocketmq:4.9.1
    container_name: mqbroker
    command: sh mqbroker -c /home/rocketmq/rocketmq-4.9.1/conf/broker.conf
    restart: always
    links:
      - mqsrv:namesrv
    environment:
      NAMESRV_ADDR: namesrv:9876
      MAX_POSSIBLE_HEAP: 200000000
    ports:
      - "10908:10908"
      - "10911:10911"

  mqconsole:
    image: apacherocketmq/rocketmq-console:2.0.0
    container_name: mqconsole
    environment:
      JAVA_OPTS: "-Drocketmq.config.namesrvAddr=192.168.146.132:9876 -Drocketmq.config.isVIPChannel=false"
    ports:
      - "8083:8080"

